#! /bin/sh

UPGRADE(){
apk update
apk upgrade
}

APK(){
apk add nano tree bash net-tools iptables wget curl procps zip unzip sudo grep
}

ADDUSER(){
export username
read -p "Type a username you want to add: " username
adduser -s /bin/bash -h /home/$username -D $username
echo -e "$username\n$username\n" | passwd $username
addgroup $username wheel
chmod 640 /etc/sudoers
echo '
%wheel ALL=(ALL) NOPASSWD: ALL
' | tee -a /etc/sudoers
#nano /etc/sudoers
}

IPFORWARD(){
echo '
net.ipv4.ip_forward = 1
net.ipv6.conf.all.disable_ipv6 = 1
' | tee -a /etc/syscyl.conf
}

PROFILE(){
echo '
alias ping='ping -c 4'
alias dir='ls -alh'
alias reboot='sudo reboot'
alias poweroff='sudo poweroff'
alias ps='ps aux'

clear

./ip
. ARauto
' | tee -a /etc/sudoers
}

AUTOLOGIN(){
apk add util-linux
echo "
tty1::respawn:/sbin/agetty --autologin $username --noclear 38400 tty1
" | tee -a /etc/inittab
nano /etc/inittab
}

setup-0(){
UPGRADE
APK
ADDUSER
IPFORWARD
PROFILE
AUTOLOGIN
}

#poweroff-----------------------------------

HOST(){
read -p "Enter hostname: " hostname
echo "$hostname
" | sudo tee /etc/hostname
echo "127.0.0.1	localhost
" | sudo tee /etc/hosts
}

ADDIP(){
echo '
auto lo
iface lo inet loopback
' | tee /etc/network/interfaces

card=$(ls /sys/class/net)
count=0
for x in $card
do

if [ $x != "lo" ];then
echo "this is $x: "

if [ $c = 0 ];then
read -p "Enter IP: " ip
read -p "Enter netmask (/number): " one
read -p "Enter gateway: " gw
echo "
auto $x
iface $x inet static
	address $ip/$one
	gateway $gw

" | sudo tee -a /etc/network/interfaces
else

read -p "Enter IP: " ip
read -p "Enter netmask(/number): " one
echo "
auto $x
iface $x inet static
	address $ip/$one

" | sudo tee -a /etc/network/interfaces
fi
c=$((c+1))
fi

done
}

ADDROUTE(){
while true
do
read -p "Destination netID: " netid
read -p "netmask: " mask
read -p "gateway: " gw
if [ -f "/etc/local.d/route_set.start" ];then
echo "route add -net $netid netmask $mask gw $gw
" | sudo tee -a /etc/local.d/route_set.start
else
echo "route add -net $netid netmask $mask gw $gw
" | sudo tee /etc/local.d/route_set.start
fi

read -p "end?(y/n) " end
case $end in
"y")
break
;;
*)
echo "continue!"
;;
esac
done
}

CHROUTE(){
sudo chmod 755 /etc/local.d/route_set.start
sudo rc-update add local
}

PROXY(){
sudo apk add squid

sudo rc-service squid start

sudo rc-update add squid
}


setup-p1(){
HOST
ADDIP
ADDROUTE
CHROUTE
PROXY
}

setup-r(){
echo "set hostname: "
HOST
echo "set IP: "
ADDIP
echo "set routing table: "
ADDROUTE
echo "chmod route_set.start"
CHROUTE
}